# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 05:41
from __future__ import unicode_literals
from django.db import migrations
from authentication.models import SignupKey


def create_signup_keys(apps, schema_editor):
    for i in range(50):
        key = SignupKey()
        key.save()


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_signup_keys)
    ]

