# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 04:06
from __future__ import unicode_literals

from django.db import migrations
from ..models import Account


def create_superuser(apps, schema_editor):
    account = Account.objects.create_superuser(first_name="Admin",
                                               last_name="Admin",
                                               email="admin@admin.com",
                                               password="swarm")


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20160319_0001'),
    ]

    operations = [
        migrations.RunPython(create_superuser)
    ]
