# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 04:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_bill', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('is_default_new_expense', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('net_income', models.FloatField(null=True)),
                ('net_hourly_pay', models.FloatField(default=0.0)),
                ('hours_worked', models.FloatField(default=0.0)),
                ('expected_cash_saved', models.FloatField(default=0.0, null=True)),
                ('interpolated_cash_saved', models.FloatField(default=0.0, null=True)),
                ('actual_cash_saved', models.FloatField(default=0.0, null=True)),
                ('avg_cash_spent_per_day', models.FloatField(default=0.0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=512)),
                ('amount', models.FloatField(default=0.0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.Category')),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.Dashboard')),
            ],
        ),
        migrations.CreateModel(
            name='IncomeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_default', models.BooleanField(verbose_name=False)),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_income', models.FloatField(default=0.0)),
                ('monthly_income', models.FloatField(default=0.0)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('income_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.IncomeType')),
            ],
        ),
        migrations.AddField(
            model_name='dashboard',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.Period'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finances.UserProfile'),
        ),
        migrations.AddField(
            model_name='category',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finances.UserProfile'),
        ),
        migrations.AddField(
            model_name='budget',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.Category'),
        ),
        migrations.AddField(
            model_name='budget',
            name='dashboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.Dashboard'),
        ),
        migrations.AddField(
            model_name='budget',
            name='expenses',
            field=models.ManyToManyField(to='finances.Expense'),
        ),
    ]
