# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 04:19
from __future__ import unicode_literals
from datetime import datetime
from ..helpers import get_period
from django.db import migrations


def create_12_periods(apps, schema_editor):
    now = datetime.now()

    month = now.month
    year = now.year
    for i in range(24):
        get_period(datetime(month=month, year=year, day=1))
        month -= 1
        if month < 1:
            month = 12
            year -= 1


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_12_periods)
    ]
