# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 04:22
from __future__ import unicode_literals

from django.db import migrations
from ..models import IncomeType


def create_income_types(apps, schema_editor):
    salary = IncomeType(name="Salary", is_default=False)
    salary.save()
    hourly = IncomeType(name="Hourly", is_default=True)
    hourly.save()


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_create_12_periods'),
    ]

    operations = [
        migrations.RunPython(create_income_types)
    ]
