# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 04:24
from __future__ import unicode_literals

from django.db import migrations
from authentication.models import Account


def create_superuser(apps, schema_editor):
    account = Account.objects.create_superuser(first_name="Method",
                                               last_name="Man",
                                               email="method@man.com",
                                               password="swarm")


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_create_income_types'),
    ]

    operations = [
        migrations.RunPython(create_superuser)
    ]
