# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 04:00
from __future__ import unicode_literals

from django.db import migrations
from ..models import IncomeType


def create_income_types(apps, schema_editor):
    salary = IncomeType(name="salary")
    salary.save()
    hourly = IncomeType(name="hourly")
    hourly.save()


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_auto_20160323_0400'),
    ]

    operations = [
        migrations.RunPython(create_income_types)
    ]
