# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 04:35
from __future__ import unicode_literals

from django.db import migrations
from ..models import Category


def create_default_categories(apps, schema_editor):
    cats = [
        Category(name="Rent", is_bill=True, is_default=True),
        Category(name="Car Loan", is_bill=True, is_default=True),
        Category(name="Car Insurance", is_bill=True, is_default=True),
        Category(name="Electricity", is_bill=True, is_default=True),
        Category(name="Gas", is_bill=True, is_default=True),
        Category(name="Phone", is_bill=True, is_default=True),

        Category(name="Restaurants & Bars", is_bill=False, is_default=True),
        Category(name="Gas & Car Costs", is_bill=False, is_default=True),
        Category(name="Groceries", is_bill=False, is_default=True),
        Category(name="Misc.", is_bill=False, is_default=True),
        ]

    for cat in cats:
        cat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0006_auto_20160323_0428'),
    ]

    operations = [
        migrations.RunPython(create_default_categories),
    ]

