# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 04:35
from __future__ import unicode_literals

from django.db import migrations
from authentication.models import Account
from ..models import UserProfile


def create_superuser(apps, schema_editor):
    account = Account.objects.create_superuser(first_name="Admin",
                                               last_name="Admin",
                                               email="admin@admin.com",
                                               password="swarm")


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0007_auto_20160323_0435'),
    ]

    operations = [
        migrations.RunPython(create_superuser)
    ]
