# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 04:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0008_auto_20160323_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='default_categories',
            field=models.ManyToManyField(to='finances.Category'),
        ),
    ]
