# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 02:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0009_auto_20160323_0444'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.Category')),
            ],
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='account',
        ),
        migrations.AddField(
            model_name='dashboard',
            name='hours_worked',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='net_hourly_pay',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finances.UserProfile'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='actual_cash_saved',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='avg_cash_spent_per_day',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='expected_cash_saved',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='interpolated_cash_saved',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='dashboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.Dashboard'),
        ),
        migrations.AddField(
            model_name='budget',
            name='expenses',
            field=models.ManyToManyField(to='finances.Expense'),
        ),
    ]
